version: '3'

services:
  web:
    container_name: bestnine-web
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - ./web:/code
    env_file: 
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    # networks:
    #   - proxy

  nginx:
    container_name: bestnine-nginx
    restart: always
    image: nginx:latest
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./nginx/bestnine.conf:/etc/nginx/conf.d/default.conf
      - ./web/html:/usr/share/nginx/html
    links:
      - web:web
    # networks:
    #   - proxy


volumes:
  web-data:

# networks:
#   proxy:
#     external:
#       name: nginx-proxy